version: '3.5'

services:
  db:
    platform: linux/amd64
    image: postgres
    restart: always
    profiles:
      - prod
      - dev
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: llm_finance
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d llm_finance"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./database/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod
      - dev
    command:
    - python
    - app/start_app.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "443:443" # If you're using Streamlit, it defaults to 8501. Change this if necessary.
    networks:
      - postgres
    volumes:
      - .:/app

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4
    restart: always
    profiles:
      - dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "80:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
